import environment
import csv
from matplotlib import pyplot as plt

env = environment.Environment()
env.time_steps()


def write_dynamics_to_csv():
    # Take dynamics and write to csv
    with open("time_dynamics.csv", mode="w", newline="") as file:
        writer = csv.writer(file)
        writer.writerow(["Time Step", "Opinion 0 Count", "Opinion 1 Count"])
        for t in range(len(env.time_dynamics[0])):
            writer.writerow([t, env.time_dynamics[0][t], env.time_dynamics[1][t]])

    # create a README file
    with open("README.txt", mode="w") as readme:
        readme.write(
            "The CSV time_dynamics.csv file contains the time dynamics of opinions in the simulation.\n"
        )
        readme.write("Columns:\n")
        readme.write("1. Time Step: The time step in the simulation.\n")
        readme.write(
            "2. Opinion 0 Count: Number of agents holding opinion 0 at that time step.\n"
        )
        readme.write(
            "3. Opinion 1 Count: Number of agents holding opinion 1 at that time step.\n"
        )
        readme.write("\nSimulation Parameters:\n")
        readme.write(f"Number of Agents: {environment.p.NUM_AGENTS}\n")
        readme.write(f"Time Steps: {environment.p.TIME_STEPS}\n")
        readme.write(
            f"Proportion of Interactions per Time Step: {environment.p.PROP_INTERACTIONS}\n"
        )
        readme.write("\nGenerated by opinion dynamics simulation script.\n")


def plot_opinion_dynamics(filename="time_dynamics.csv"):
    """Plot the opinion dynamics over time."""
    # Open the CSV and plot the time dynamics
    with open(filename, mode="r") as file:
        reader = csv.reader(file)
        next(reader)  # Skip header
        time_steps = []
        opinion_0_counts = []
        opinion_1_counts = []
        for row in reader:
            time_steps.append(int(row[0]))
            opinion_0_counts.append(float(row[1]))
            opinion_1_counts.append(float(row[2]))

        plt.scatter(
            range(len(opinion_0_counts)),
            opinion_0_counts,
            label="Opinion 0s",
        )
        plt.scatter(range(len(opinion_1_counts)), opinion_1_counts, label="Opinion 1s")
        plt.xlabel("Time Steps")
        plt.ylabel("Proportion of Agents")
        plt.title("Opinion Dynamics Over Time")
        plt.legend()
        plt.savefig("time_dynamics.png")
        plt.close()


write_dynamics_to_csv()
plot_opinion_dynamics()
