import environment

import csv
from matplotlib import pyplot as plt  # type: ignore


def write_dynamics_to_csv():
    # Take dynamics and write to csv
    with open("time_dynamics_m2.csv", mode="w", newline="") as file:
        writer = csv.writer(file)
        writer.writerow(
            ["Time Step", "Opinion Mean", "Opinion SD", "Friends Mean", "Friends SD"]
        )
        for t in range(len(env.opinions)):
            writer.writerow(
                [
                    t,
                    env.opinions[t][0],
                    env.opinions[t][1],
                    env.opinions[t][2],
                    env.opinions[t][3],
                ]
            )

    # create a README file
    with open("README2.txt", mode="w") as readme:
        readme.write(
            "The CSV time_dynamics_m2.csv file contains the time dynamics of opinions in the simulation.\n"
        )
        readme.write("Columns:\n")
        readme.write("1. Time Step: The time step in the simulation.\n")
        readme.write("2. Opinion Mean: Mean opinion of all agents at that time step.\n")
        readme.write(
            "3. Opinion SD: Standard deviation of opinions of all agents at that time step.\n"
        )
        readme.write(
            "4. Friends Mean: Mean number of friends per agent at that time step.\n"
        )
        readme.write(
            "5. Friends SD: Standard deviation of number of friends per agent at that time step.\n"
        )
        readme.write("\nSimulation Parameters:\n")
        readme.write(f"Number of Agents: {environment.p.NUM_AGENTS}\n")
        readme.write(f"Time Steps: {environment.p.TIME_STEPS}\n")
        readme.write(
            f"Proportion of Interactions per Time Step: {environment.p.PROP_INTERACTIONS}\n"
        )
        readme.write("\nGenerated by opinion dynamics simulation script.\n")


def plot_opinion_dynamics(filename="time_dynamics_m2.csv"):
    """Plot the opinion dynamics over time."""
    # Open the CSV and plot the time dynamics
    with open(filename, mode="r") as file:
        reader = csv.reader(file)
        next(reader)  # Skip header
        time_steps = []
        opinion_mean = []
        opinion_std = []
        friends_mean = []
        friends_std = []

        for row in reader:
            time_steps.append(int(row[0]))
            opinion_mean.append(float(row[1]))
            opinion_std.append(float(row[2]))
            friends_mean.append(float(row[3]))
            friends_std.append(float(row[4]))
        plt.plot(
            range(len(opinion_mean)),
            opinion_mean,
            label="Opinion Mean",
        )
        plt.plot(range(len(opinion_std)), opinion_std, label="Opinion Std Deviation")
        plt.plot(
            range(len(friends_mean)),
            friends_mean,
            label="Friends Mean",
        )
        plt.plot(
            range(len(friends_std)),
            friends_std,
            label="Friends Std Deviation",
        )
        plt.ylabel("Value")
        plt.xlabel("Time Steps")
        plt.title("Opinion Dynamics Over Time")
        plt.legend()
        plt.savefig("time_dynamics_m2.png")
        plt.close()


env = environment.Environment()
# env.plot_network()
env.time_steps()
write_dynamics_to_csv()
plot_opinion_dynamics()
